### PR TITLE
Added Java notes 

### LINKED ISSUE #4: add java notes for better understanding

### PR DESCRIPTION
**Pull request by thesumitkrsingh**
add java notes for better understanding #4  issues fixes #4 and closed #4

### CODE REVIEW

**Comment by thesumitkrsingh** [comment]
#4 i added the java notes  the issues fixes #4 and closes #4

**Comment by thesumitkrsingh** [comment]
add the resources to the main branch

**Comment by 18praneeth** [comment]
Hi,
This notes is not related to Programs, If you are adding it as part of general purpose notes I advice you to create a new repo, PDF format are not readable in github and source control does not work well with binary files

**Comment by thesumitkrsingh** [comment]
> add java notes for better understanding #4  issues fixes #4 and closed #4

    Ok 👍

**Pull request closed without merging**
